# -*- coding: utf-8 -*-

# Generated by Django 2.1.4 on 2021-08-31 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dblist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(default='', max_length=30)),
                ('type', models.CharField(default='', max_length=30)),
                ('updated_time', models.DateTimeField()),
                ('created_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(default='', max_length=30)),
                ('login_name', models.CharField(default='', max_length=20, unique=True)),
                ('login_pwd', models.CharField(default='', max_length=32)),
                ('login_salt', models.CharField(default='', max_length=32)),
                ('status', models.IntegerField(default=1)),
                ('updated_time', models.DateTimeField()),
                ('created_time', models.DateTimeField()),
            ],
        ),
    ]
