# Generated by Django 2.2.10 on 2021-11-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealDblist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(default='', max_length=30)),
                ('type', models.CharField(default='', max_length=30)),
                ('updated_time', models.DateTimeField()),
                ('created_time', models.DateTimeField()),
            ],
        ),
    ]
